name: Staging TearDown CI
on:
  workflow_dispatch:

jobs:
  staging:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.1  

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: terraform init
      working-directory: ./infra/
      run: terraform init
              
    - name: terraform destroy - K8S
      working-directory: ./infra/modules/k8s
      run: terraform destroy -auto-approve -target=module.k8s

    - name: terraform destroy - EKS
      working-directory: ./infra/modules/eks
      run: terraform destroy -auto-approve -target=module.eks

    - name: terraform destroy - VPC
      working-directory: ./infra/modules/vpc
      run: terraform destroy -auto-approve -target=module.vpc     
      