name: Staging TearDown CI
on:
  workflow_dispatch:

jobs:
  staging:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.1  

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: terraform init
      run: terraform init

    - name: terraform plan
      uses: dflook/terraform-plan@v1
              
    - name: terraform destroy - K8S with Debug and Parallelism
      working-directory: ./modules/k8s
      run: |
        TF_LOG=DEBUG terraform destroy -auto-approve -target=module.k8s -parallelism=2

    - name: terraform destroy - EKS with Parallelism
      working-directory: ./modules/eks
      run: terraform destroy -auto-approve -target=module.eks -parallelism=2

    - name: terraform destroy - VPC with Parallelism
      working-directory: ./modules/vpc
      run: terraform destroy -auto-approve -target=module.vpc -parallelism=2
  
      