name: Staging CI
on:
  workflow_dispatch:
jobs:
  staging:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.1

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1      

    - name: Terraform Init
      working-directory: ./infra/
      run: terraform init
    
    - name: terraform apply - VPC
      working-directory: ./infra/
      run: |
        terraform apply -auto-approve -target=module.vpc

    - name: terraform apply - EKS
      working-directory: ./infra/
      run: |
        terraform apply -auto-approve -target=module.eks
         
    - name: Build & push Docker image to AWS ECR for react app
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ${{ secrets.AWS_ECR_REGISTRY }}/react_app
        tags: latest
        registry: ${{ secrets.AWS_ECR_REGISTRY }}
        dockerfile: ./docker-compose.ci.yml
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & push Docker image to AWS ECR for node app
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ${{ secrets.AWS_ECR_REGISTRY }}/node_app
        tags: latest
        registry: ${{ secrets.AWS_ECR_REGISTRY }}
        dockerfile: ./docker-compose.ci.yml
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: terraform apply - K8S
      working-directory: ./infra/
      run: |
        terraform apply -auto-approve -target=module.k8s