name: Staging TearDown CI
on:
  workflow_dispatch:

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1   

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.1  

    - name: terraform init
      working-diectory: ./infra/
      run: terraform init
    
    - name: Destroy K8S resources
      working-directory: ./infra/
      run: terraform destroy -auto-approve -target=module.k8s

    - name: Destroy EKS resources
      working-directory: ./infra/
      run: terraform destroy -auto-approve -target=module.eks  

    - name: Destroy K8S VPC
      working-directory: ./infra/
      run: terraform destroy -auto-approve -target=module.vpc
      