name: Staging CI
on:
  workflow_dispatch:

jobs:
  terraform-staging:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.1
    
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    # Apply Plan configurations
    - name: Terraform init and validate
      working-directory: ./
      run: |
        terraform init
        terraform validate -no-color

    - name: Terraform Plan - VPC
      working-directory: ./modules/vpc/
      run: terraform plan -no-color
      continue-on-error: true

    - name: Terraform Plan - EKS
      working-directory: ./modules/eks/
      run: terraform plan -no-color
      continue-on-error: true

    - name: Terraform Plan - K8S
      working-directory: ./modules/k8s/
      run: terraform plan -no-color
      continue-on-error: true    

    # Apply Terraform configurations for VPC
    - name: Terraform Init - VPC
      working-directory: ./modules/vpc/
      run: terraform init

    - name: Terraform Apply - VPC
      working-directory: ./modules/vpc/
      run: terraform apply -auto-approve

    # Apply Terraform configurations for EKS
    - name: Terraform Init - EKS
      working-directory: ./modules/eks/
      run: terraform init

    - name: Terraform Apply - EKS
      working-directory: ./modules/eks/
      run: terraform apply -auto-approve

    - name: Terraform Output - EKS
      working-directory: ./modules/eks/
      run: terraform output   

    # Build and push Docker images to ECR
    - name: Log in to Amazon ECR
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}

    - name: Build & push Docker image to AWS ECR for react app
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: react_app
        tags: latest
        registry: ${{ secrets.AWS_ECR_REGISTRY }}
        dockerfile: ./docker-compose.ci.yml
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & push Docker image to AWS ECR for node app
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: node_app
        tags: latest
        registry: ${{ secrets.AWS_ECR_REGISTRY }}
        dockerfile: ./docker-compose.ci.yml
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # Apply Terraform configurations for K8S
    - name: Terraform Init - K8S
      working-directory: ./modules/k8s/
      run: terraform init

    - name: Terraform Apply - K8S
      working-directory: ./modules/k8s/
      run: terraform apply -auto-approve
    
    - name: Terraform Output - K8S
      working-directory: ./modules/k8s/
      run: terraform output   